pipelines:
  default:
    - step:
        name: Build
        image: microsoft/dotnet
        script:
          - dotnet --version
          - dotnet restore
          - dotnet build
          - dotnet test
        artifacts:
          - ParkingLotApi/bin/**
          - ParkingLotApi.Tests/bin/**